### ISSUE TITLE
Open up Octostache to allow extraction of replacement tokens

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Octostache#19]
https://secure.helpscout.net/conversation/592362894?folderId=845296 (private link)

If you have a file that is formatted with OctoStache variable replacements, it would be good to be able to write a program that parses the file and returns an array of all the variables.

With this data, for example, the user could add prompted variable to Octopus automatically

**Comment by andrewsav-datacom** [comment]
Thank you very much for listening. Tested this, works very well for our purposes. @droyad
