### ISSUE TITLE
Filters like PeriodsToHypens, HypensToUnderscores etc

### ISSUE THREAD

**Issue by mcintyre321** [OctopusDeploy/Octostache#24]
Our environment names are things like `dev.mysite.com` and it would be helpful to be able to insert a cleaned up version of these these into other variables without the special characters e.g. so that they can be used in a database name.

It would be great to have a few filters like `PeriodsToHypens`, `HypensToUnderscores`, `UnderscoresToPeriods` etc. which could be used to make the variables safe.

**Comment by droyad** [comment]
We could add a Regex replace filter

**Comment by droyad** [comment]
Just saw #23, that possibly would  cover your needs?

**Comment by mcintyre321** [comment]
Yes I think it does :) thanks!
