### ISSUE TITLE
Iterating over Octopus.Action returns instances in the improper order

### ISSUE THREAD

**Issue by omon77** [OctopusDeploy/Octostache#28]
Using a sample email template from here: [https://octopus.com/docs/deployment-process/steps/email-notifications](https://octopus.com/docs/deployment-process/steps/email-notifications), the iterator over Octopus.Action collection
`#{each action in Octopus.Action}
....
#{/each}`
consistently lists the last step as first.
In OD process, the steps are:
1) Deploy Process
2) Start service
3) Send Email notification using the template.

The email arrives consistently listing the actions in the following order:
1) Send Email notification using the template.
2) Deploy Process
3) Start service

Using Octopus v2018.8.4

**Comment by droyad** [comment]
This isn't a problem with Octostache as it just returns the items as they are in the collection. It has no way of knowing what the proper order is. My guess is that your email notification step is only set to run when a failure occurs. There isn't an easy way to resolve this unfortunately. If you need further assistance, please contact us via our [support channels](https://octopus.com/support)
