### ISSUE TITLE
missing Octopus.Versioning  nuget

### ISSUE THREAD

**Issue by SimonCropp** [OctopusDeploy/Octostache#50]
Octostache 2.9.2 depends on  Octopus.Versioning (>= 4.2.3), but that version doesnt exist https://www.nuget.org/packages/Octopus.Versioning/

![image](https://user-images.githubusercontent.com/122666/95263801-179b0600-087a-11eb-9eca-3ae453a382ec.png)

**Comment by droyad** [comment]
Looks like we added that dependency in `2.9.2` as part of #48 (cc @mcasperson).

 I'm not sure what we should do here. Thoughts about whether we publish `Octopus.Versioning` to NuGet @slewis74? Alternatively should we IL merge it? ([this says exes](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables) but perhaps libs work too)

@SimonCropp Thanks for the heads up. Until we get this rectified, the missing package is available using the feed
https://f.feedz.io/octopus-deploy/dependencies/nuget/index.json

**Comment by mcasperson** [comment]
My apologies, I didn't realize the versioning library was not on NuGet. To facilitate scenarios like feature branch deployments we plan to lean on Octostache to work with version strings, so it probably makes sense to publish the versioning library.

**Comment by slewis74** [comment]
That package should be public, I'll get it published.

**Comment by SimonCropp** [comment]
same problem is occurring now 
![image](https://user-images.githubusercontent.com/122666/154182196-cd081578-7b41-4e18-b069-32a33e05ee8e.png)

**Comment by N-lson** [comment]
Thanks for raising this issue again @SimonCropp. The required version has been pushed to Nuget. Apologies for the inconvenience 🙇

**Comment by SimonCropp** [comment]
@N-lson thanks
